services:
  caddy:
    image: caddy:2.7-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - n8n-services
    mem_limit: 128m
    mem_reservation: 64m

  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.${URL_SUBDOMAIN}/grafana
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,redis-datasource
    networks:
      - n8n-services
    volumes:
      - ./data/grafana:/var/lib/grafana
    mem_limit: 512m
    mem_reservation: 256m

  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    ports:
      - "3000:3000"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'
    environment:
      - WHATSAPP_API_PORT=3000
      - WHATSAPP_DEFAULT_ENGINE=GOWS
      - WHATSAPP_DASHBOARD_ENABLED=true
      - WAHA_DASHBOARD_USERNAME=${WAHA_USERNAME}
      - WAHA_DASHBOARD_PASSWORD=${WAHA_PASSWORD}
      - WHATSAPP_SWAGGER_ENABLED=true
      - WHATSAPP_SWAGGER_USERNAME=${WAHA_USERNAME}
      - WHATSAPP_SWAGGER_PASSWORD=${WAHA_PASSWORD}
      - WAHA_PRINT_QR=False
      - WHATSAPP_HOOK_URL=https://waha.${URL_SUBDOMAIN}/whats/webhook
      - WHATSAPP_HOOK_EVENTS=session.status,message,message.reaction
      - TZ=America/Sao_Paulo
    networks:
      - n8n-services
    volumes:
      - ./data/waha/sessions:/app/.sessions
      - ./data/waha/media:/app/.media
    mem_limit: 512m
    mem_reservation: 256m

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - n8n-services
    volumes:
      - ./data/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    mem_limit: 1g
    mem_reservation: 512m

volumes:
  caddy_data:
  caddy_config:

networks:
  n8n-services:
    driver: bridge
